### PR TITLE
Auth0 and loading screen

### PR DESCRIPTION
**Pull request by cindoum**
Here is a PR for a fully working authentication system. 
I also added a loading page while wainting for bootstraping.

It is not perfect yet but fully functionnal.

Ive set the firebase rule to not allow a not authenticated user read/write the client table.

I started deleting spec file as for now i fond it useless and i dont think it belong here (i think a /test folder would be more appropriate).

Can you manully do the merge to not drop your test files?

### CODE REVIEW

**Comment by cindoum** [comment]
linked to #29 .

Sorry for the long delay, just got a new son 2 weeks ago so its hard to find some free time ;)

**Comment by TwanoO67** [comment]
Congratulations for your son :D 
And thanks a lot for the PR :)

**Comment by TwanoO67** [comment]
I just reviewed the PR, it looks very nice! :D 

One question, I saw you added @types/lodash, is there specific of your installation or do we need that (as we removed the _ lib that was unused in your last PR) ?

**Comment by TwanoO67** [comment]
By the way, on your auth.service.ts you have your login information. 
You are sure that this time it is testing values ? ^^

**Comment by cindoum** [comment]
thanks.

for the @types/lodash you can still remove it. its the typing of the lodash lib thai we removed on the last PR. dont know its still there...

for the auth0 info its ok. I left then in the code source the app can be tested without having to create and setup an accout.  these info belong in a client app so its safe

**Pull request merged**
